### ISSUE TITLE
Dark Sections

### ISSUE THREAD

**Issue by PritchardGSD** [ericwa/tyrutils-ericw#119]
Not sure if creating this issue is a good idea or not, but I suppose it can't hurt.
http://i.imgur.com/mMEvsmF.png
http://i.imgur.com/tGyDlsm.jpg

Basically, when a brush and another brush are barely touching, light can generate these dark areas that are demonstrated in the second image. It's pretty ugly.

Not sure what else to say, other than this is not a new issue and may have even been discussed before. I've seen it in several versions of this tool, I haven't tested others.

**Comment by ericwa** [comment]
Thanks (reporting bugs here is great, easier to keep track of than forums :) - this is a limitation dating back to the original tool from ID.

I have an existing issue for it so I'll close this one. https://github.com/ericwa/tyrutils-ericw/issues/8

Also, have a fix in mind which I will hopefully code for the next version!
