### ISSUE TITLE
Hexen 2 origin brush for rotating entities doesn't work

### ISSUE THREAD

**Issue by Bloodshot12** [ericwa/tyrutils-ericw#124]
Posted in func_msgboard, posting here as well as it makes more sense. Hexen 2 supports the use of origin brushes like half-life for rotating entities, but qbsp with -hexen2 does not recognize it and treats it as a regular texture that shows up ingame

**Comment by ericwa** [comment]
Tried to throw together origin brush support in cc71ad02

Here is a build:
https://ci.appveyor.com/api/buildjobs/scnsbbasbt5nun18/artifacts/cmakebuild%2Ftyrutils-ericw-v0.15.9-2-gcc71ad0-win32.zip

**Comment by muk0r** [comment]
Just name a texture "origin" and make an "origin" brush with said texture?

**Comment by ericwa** [comment]
Yeah, just a cube with all faces using a texture called "origin". 

I tested it with hipnotic, and a `func_rotate_entity` + `rotate_object` + `info_rotate` setup. The origin brush goes in the `rotate_object`, and you can delete the info_rotate and the target connection between the rotate_object and the info_rotate. Not a huge advantage, but it saves an entity.

It *might* work with that "rotating func_wall in id1" hack.. not sure

**Comment by Bloodshot12** [comment]
That was quick. Now hexen 2 has a new problem though, The entity has no collision when done this way. I assume it might have something to do with hexen 2 having true rotation and using the collision of the actual func_door_rotating?

**Comment by ericwa** [comment]
Cool, well at least it's partly working.. I'll need to test it out in Hexen 2.
Yeah, Hexen 2 has true collision against rotating brushes unlike Quake.

**Comment by ericwa** [comment]
@Bloodshot12 Found the bug! There is a test map included in the archive `testmaps/h2rotation.map` with a rotating door, collision is working for me now.

https://ci.appveyor.com/api/buildjobs/w21q4kj8bbde9966/artifacts/cmakebuild%2Ftyrutils-ericw-v0.15.9-6-g2637373-win32.zip
