### ISSUE TITLE
Give more debug information when "CalcualateVertexNormals" in light.exe finds an error

### ISSUE THREAD

**Issue by tdDaz** [ericwa/tyrutils-ericw#165]
Current debug info when light fails with this message:

--- LightWorld ---
CalcualateVertexNormals: face 22768 is degenerate with 2 edges

Expected debug info:

Give a brush number or coordinates to track down the face causing the issue.

More info : 
Editor used J.A.C.K
Valve 220 texture coordinates
light version : tyrutils-ericw-v0.15.10-beta2-win64
This error did not occur on previous version used which was v0.15.4

**Comment by ericwa** [comment]
Thanks, just modified it to print the coordinates.

I also made this error non-fatal a few weeks ago, just need to make a new beta release which I'll do later today!

**Comment by tdDaz** [comment]
<3
