### ISSUE TITLE
Light quality regression?

### ISSUE THREAD

**Issue by PritchardGSD** [ericwa/tyrutils-ericw#171]
There seem to be some issues with 0.15.10's light.exe still. Here's what I get when I compile with that build:

https://i.imgur.com/Tuub6Pe.jpg (-extra4 -soft)

and here's what I get when I use 0.15.9

https://i.imgur.com/J1dwbIt.jpg

It's not perfect either actually, but in general it generates far fewer hard edges/seams.

,map file: (change the file extension obviously)
[adventjam_pritchard.map.txt](https://github.com/ericwa/tyrutils-ericw/files/1274675/adventjam_pritchard.map.txt)

**Comment by ericwa** [comment]
Investigated a bit.. (btw I adjusted the _sun_mangle to `0 -90 0` to match your screenshot.)

Seems like there are two things contributing to seams.
- 0.15.10's light.exe really needs tjuncs to work properly, and qbsp only generates them if the map is sealed.
- 0.15.10's `-soft` flag seems to be broken, at least, it generates a strong seam.

My screenshots:
- not sealed, light args: `-extra4`
![spasm0000](https://user-images.githubusercontent.com/239161/30505942-17997fe4-9a35-11e7-885c-8af15bfe25bc.png)
- sealed, light args: `-extra4`
![spasm0001](https://user-images.githubusercontent.com/239161/30505956-36f378fe-9a35-11e7-829b-59dc55d1fa8d.png)
- sealed, light args: `-soft -extra4`
![spasm0002](https://user-images.githubusercontent.com/239161/30505967-575954c4-9a35-11e7-9ea4-2f3cbf91e04b.png)

**Comment by ericwa** [comment]
I tweaked `-soft` in 7252ba78416426809459c432f427c814a99d2878 and it looks better now:

![spasm0005](https://user-images.githubusercontent.com/239161/30516845-60bbf92c-9b07-11e7-8cf0-f07e8c7d4110.png)

that is with `-extra4 -soft` and the map sealed.

I realize having seams appear when the map is unsealed is annoying, made an issue for that https://github.com/ericwa/tyrutils-ericw/issues/177
