### ISSUE TITLE
Strange lightmap with custom -lmscale

### ISSUE THREAD

**Issue by danpla** [ericwa/tyrutils-ericw#180]
I tried -lmscale with 32 instead of the default 16 and got the following:
![spasm0002](https://user-images.githubusercontent.com/10910745/30776532-ba70c188-a0b0-11e7-8f0c-1b0c32b43f18.jpg)

**Comment by ericwa** [comment]
Which engine is that? `-lmscale` produces bsp's that only work in FTEQW, and will look like your screenshot in other engines.. so it's not really useful for general use.

**Comment by danpla** [comment]
Ah, thanks for the explanation. It would be nice to add a note in the docs.
