### ISSUE TITLE
added support for unversioned BSP files just like juggernaut maps

### ISSUE THREAD

**Issue by mckaygerhard** [ericwa/tyrutils-ericw#2]
the juggernaut bsp files has no property set version, and must be edited to property handled in linux

so the bsp files must be altered or regenerated to change the paths to a lowercase due case-sensity are mandatory in real operating systems such like linux, unix, freebsd or mac

when i try to use the tools in a juggernaut bsp file i got that result:
```
JDM1.BSP
BSP is version 1347633737
************ ERROR ************
```

**Comment by ericwa** [comment]
Hey, what's Juggernaut? is it possible to download JDM1.BSP anywhere?

**Comment by mckaygerhard** [comment]
i can post a shared link, but wheantime was investigate and its possible that those files are a q2 compiled maps and original tyrutils handles only q1 compiles maps.. its that true?

**Comment by ericwa** [comment]
Oh ok, yeah, original tyrutils as well as this fork only handle q1, there is no q2 support. 
I just searched for 1347633737 and that is the "IBSP" header, which is Q2/Q3 bsp, I think.

**Comment by ericwa** [comment]
I think q2/q3bsp support is out of scope of this project, sorry.

**Comment by mckaygerhard** [comment]
hi, long time ago... there's another editor for that files that not need extra files, just a light and fast single like tyrutils like?

the juggernauth maps have hard coded paths with case insensitive, forced me to handle that in source code of engine!

well thanks ion advance that true, its out of scope.

**Comment by ericwa** [comment]
Hey, q3map2 is the only option for q3bsp games (it's distributed with gtkradiant). Not sure if that supports Juggernaut?

**Comment by mckaygerhard** [comment]
yeah q3map2 but as u said, comes includes in gtkradiant.. grr gtkradiant does not allow to compalint debina packagin standards, take too many resources from network.

i tri it download separatelly but the only way today its in gtkradiant.. well thanks i'll use the gtkradiant to made it!
