### ISSUE TITLE
Build error due to using C99 constructs

### ISSUE THREAD

**Issue by kduske** [ericwa/tyrutils-ericw#37]
kristian@kristian-Parallels-Virtual-Platform:~/Documents/tyrutils-ericw/build$ cmake --build .
	Scanning dependencies of target man_bspinfo
	[  1%] Generating bspinfo.html
	[  1%] Built target man_bspinfo
	Scanning dependencies of target bspinfo
	[  3%] Building C object bspinfo/CMakeFiles/bspinfo.dir/bspinfo.c.o
	[  5%] Building C object bspinfo/CMakeFiles/bspinfo.dir/__/common/cmdlib.c.o
	[  7%] Building C object bspinfo/CMakeFiles/bspinfo.dir/__/common/bspfile.c.o
	[  8%] Building C object bspinfo/CMakeFiles/bspinfo.dir/__/common/log.c.o
	[ 10%] Building C object bspinfo/CMakeFiles/bspinfo.dir/__/common/threads.c.o
	Linking C executable bspinfo
	[ 10%] Built target bspinfo
	Scanning dependencies of target man_bsputil
	[ 12%] Generating bsputil.html
	[ 12%] Built target man_bsputil
	Scanning dependencies of target bsputil
	[ 14%] Building C object bsputil/CMakeFiles/bsputil.dir/bsputil.c.o
	[ 15%] Building C object bsputil/CMakeFiles/bsputil.dir/__/common/cmdlib.c.o
	[ 17%] Building C object bsputil/CMakeFiles/bsputil.dir/__/common/bspfile.c.o
	[ 19%] Building C object bsputil/CMakeFiles/bsputil.dir/__/common/log.c.o
	[ 21%] Building C object bsputil/CMakeFiles/bsputil.dir/__/common/threads.c.o
	Linking C executable bsputil
	[ 21%] Built target bsputil
	Scanning dependencies of target man_light
	[ 22%] Generating light.html
	[ 22%] Built target man_light
	Scanning dependencies of target light
	[ 24%] Building C object light/CMakeFiles/light.dir/entities.c.o
	[ 26%] Building C object light/CMakeFiles/light.dir/litfile.c.o
	[ 28%] Building C object light/CMakeFiles/light.dir/ltface.c.o
	/home/kristian/Documents/tyrutils-ericw/light/ltface.c: In function ‘CheckObstructed’:
	/home/kristian/Documents/tyrutils-ericw/light/ltface.c:585:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
	     for (int x = -1; x <= 1; x += 2) {
	     ^
	/home/kristian/Documents/tyrutils-ericw/light/ltface.c:585:5: note: use option -std=c99 or -std=gnu99 to compile your code
	/home/kristian/Documents/tyrutils-ericw/light/ltface.c:586:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
	         for (int y = -1; y <= 1; y += 2) {
	         ^
	/home/kristian/Documents/tyrutils-ericw/light/ltface.c: In function ‘CalcPoints’:
	/home/kristian/Documents/tyrutils-ericw/light/ltface.c:638:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
	     for (int t = 0; t < surf->height; t++) {
	     ^
	/home/kristian/Documents/tyrutils-ericw/light/ltface.c:639:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
	         for (int s = 0; s < surf->width; s++) {
	         ^
	make[2]: *** [light/CMakeFiles/light.dir/ltface.c.o] Error 1
	make[1]: *** [light/CMakeFiles/light.dir/all] Error 2
	make: *** [all] Error 2

**Comment by ericwa** [comment]
Argh. b087f0f010cc73f3797b1698a0d4a50c228b47f9 should fix this, hopefully

**Comment by kduske** [comment]
Yup, builds fine now. Thanks!
