### ISSUE TITLE
Crash when lighting a sealed map

### ISSUE THREAD

**Issue by PritchardGSD** [ericwa/tyrutils-ericw#70]
I sealed my map to test vis times and so on, and suddenly my light tool started to crash.
For what it's worth, I tested with the original tyrutils and there was no crash. 

Here is an example of the console output when I'm building my map:
`Source File:lavabloom.bsp
TxQBSP 1.13 -- Modified by Bengt Jardrup

Inputfile: maps\lavabloom.map
Outputfile: maps\lavabloom.bsp
------ LoadMapFile ------
 17416 faces
  2632 brushes
   328 entities
   102 miptex
  2159 texinfo
Added 2 texture frames
WARNING: Texture __tb_empty not found

Building hulls sequentially...
Processing hull 0...
------ Brush_LoadEntity ------
----+----+
  2326 brushes read
------ CSGFaces ------
----+----+
 15506 brushfaces
 18032 csgfaces
 13044 mergedfaces
------ SolidBSP ------
 17750 split nodes
  7795 solid leafs
  8734 empty leafs
  1222 water leafs
 31659 leaffaces
 27738 nodefaces
WARNING: CutNodePortals_r: New portal was clipped away near (2614 1398 280)
WARNING: CutNodePortals_r: New portal was clipped away near (1744 1555 -160)
------ FillOutside ------
  2978 outleafs
------ MergeAll ------
 10490 mergefaces
------ SolidBSP ------
----+----+
  7730 split nodes
  3751 solid leafs
  3362 empty leafs
   618 water leafs
 18137 leaffaces
 13750 nodefaces
------ Portalize ------
WARNING: CutNodePortals_r: New portal was clipped away near (2591 1504 -465)
  3980 vis leafs
 12439 vis portals
------ Tjunc ------
 13234 world edges
 44912 edge points
 10856 edges added by tjunctions
     0 faces added by tjunctions
------ MakeFaceEdges ------
----+----+
------ GrowRegions ------
Processing hull 1...
----+---\
WARNING: CheckFace: Healing point (1296 -22 128) off plane by -0.4
WARNING: CheckFace: Healing point (1264 -22 128) off plane by -0.4
----+----+
----+----+
WARNING: CutNodePortals_r: New portal was clipped away near (1376 -48 -72)
WARNING: CutNodePortals_r: New portal was clipped away near (1312 144 119)
Processing hull 2...
----+----\
WARNING: CheckFace: Healing point (-240 -320 -368) off plane by -1.37
WARNING: CheckFace: Healing point (-352 -240 -400) off plane by -1.85
WARNING: CheckFace: Healing point (-352 -304 -400) off plane by -1.85
WARNING: CheckFace: Healing point (-240 -384 -368) off plane by -1.37
----+----+
----+----+

------ FinishBSPFile ------
WriteBSPFile: maps\lavabloom.bsp
  7342 planes       146840
 17458 vertexes     209496
  8563 nodes        205512
  2159 texinfo       86360
 14928 faces        298560
 15243 clipnodes    121944
  4644 leafs        130032
 19359 marksurfaces  38718
 68073 surfedges    272292
 34542 edges        138168
   104 textures    1256080
       lightdata         0
       visdata           0
       entdata       36878

12 warnings

Elapsed time : 0:10

Peak memory used : 19.3 MB
---- light / TyrUtils ericw-v0.15.5 ----
running with 8 threads
BSP is version 29
Colored light entities detected: .lit output enabled.
328 entities read, 144 are lights.
FindLights: 144 total lights
--- LightWorld ---
0....1....2.        1 file(s) copied.
The system cannot find the file specified.
Done!
Press Y to test map, N to quit [Y,N]?`

And here's a zip file with a "crash" and "no crash" version of the .map, along with some images demonstrating what changes when i seal the map: 
[lavabloom_crash.zip](https://github.com/ericwa/tyrutils-ericw/files/356584/lavabloom_crash.zip)

**Comment by PritchardGSD** [comment]
False alarm: the issue seems to have been caused by the bsp tool in use, rather than light.exe

**Comment by ericwa** [comment]
Both underlying issues are fixed:
https://github.com/ericwa/tyrutils-ericw/issues/71
https://github.com/ericwa/tyrutils-ericw/issues/72
